controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# the "app_lucky_number" route name is not important yet
home:
    path: /
    controller: App\Controller\HomeController::index

ibigo:
    path: /ibigo
    controller: App\Controller\IbigoController::index

fruitbook:
    path: /fruitbook
    controller: App\Controller\FruitBookController::index

isuperordi:
    path: /isuperordi
    controller: App\Controller\IsuperOrdiController::index

imontre:
    path: /imontre
    controller: App\Controller\ImontreController::index

ibigbigo:
    path: /ibigbigo
    controller: App\Controller\IbigBigoController::index

iecouteur:
    path: /iecouteur
    controller: App\Controller\IecouteurController::index

ibigoform:
    path: /submitformibigo
    controller: App\Controller\IbigoController::submit